### PR TITLE
Full Compatibility with Monolog 3.6

### LINKED ISSUE #15: `$logger->notice()` should be resolved to `WP_CLI::log` instead of `WP_CLI::warning`
Hi @markheydon, thanks for this little package! This is not really a bug, but rather a design question.

Regarding to the documentation of Monolog:

> **NOTICE** (250): Normal but significant events.

This should not trigger a `WP_CLI::warning`, but rather just a simple `WP_CLI::log`:

```php
$logger->notice('Something normal but significant happened');
```

What do you think? Happy to create a PR if you agree.

### PR DESCRIPTION
**Pull request by hirasso**
Warning: This PR is huge.

I'm opening it here to let you have a look if you are interested. If it's just too many changes for your taste, I'll continue to maintain my fork for my use.

- PHP 8.2
- Monolog ^3.6
- Also fixes #15 
- New class `LoggerMapEntry` that simplifies the whole thing significantly due to type safety
- Removal of a lot of tests since the `LoggerMapEntry` catches almost all cases
- New major version: `2.0.0`
- Pretty-prints provided context using [symphony/var-dumper](https://symfony.com/doc/current/components/var_dumper.html)

Questions:

- There where a lot of weird comments that I couldn't make sense of, for example `//<editor-fold desc="Private helper methods">. Removed all of them from the code as they seemed IDE-specific to me
- If you decide to continue maintaining the package, we should think about a github action to run the tests in PRs. I could help out there as I'm a maintainer of [another rather large open source repo](https://github.com/swup/swup).

### CODE REVIEW

**Comment by markheydon** [comment]
Thanks for this @hirasso, very true I've struggled to get to updating it to latest versions of stuff so your efforts are appreciated!

Not sure what you mean on the 'weird comments', I couldn't see anything in the changes that take out anything that looked odd. That said, I did at some point use IDEs other than VS Code, in particular I remember one of them (PHP Storm maybe?) that used to do something odd with comments.

You mention Actions too, there's some already, aren't they doing what you suggest? Or did I miss something?

**Comment by hirasso** [comment]
Hey @markheydon! Great to know you're open to my contribution! I saw the action notification about the failing tests. Could we update the PHP version in the action to 8.2? Since Monolog ^3 requires at least PHP 8.1, I figure most users of this package likely keep their PHP updated.

Regarding the code comments I deleted, I also believe they're related to PHP Storm. One example: 

```php
//<editor-fold desc="Magic Methods">
```

Also, it's possible the code coverage dropped below 100% in my PR since I'm not familiar with coverage tools. However, I prioritize writing tests for critical components, so I don't think it's a big issue. I prefer keeping my repos free of coverage report batches.

**Comment by hirasso** [comment]
I've ditched the idea of using WP_CLI together with Monolog logs, so I'll close this PR. Turns out there is a much simpler solution with simply using `php://output`. That also makes it pretty straightforward to dump the `context` of a `LogRecord` using Symphony's VarDumper package. I've posted my new solution over at StackOverflow: https://stackoverflow.com/a/78447765/586823

**Comment by markheydon** [comment]
Thanks for the update @hirasso, was good to have some interest in the project while it lasted though!

**Pull request closed without merging**
